
#ifndef CONSTANTS_H
#define CONSTANTS_H

// COLORS
#define COL_CYAN 0x07FF
#define COL_RED 0xf800
#define COL_BLUE 0x001F
#define COL_GREEN 0x07E0
#define COL_MAGENTA 0xF81F
#define COL_WHITE 0xffff
#define COL_BLACK 0x0000
#define COL_YELLOW 0xFFE0
#define COL_DARK_GREY 0x8410

// GEOMETRY
#define GEO_PIXEL_SIZE 4
#define GEO_INV_GRID_DIM 8
#define GEO_INV_COLLISION_THRESH 32
#define GEO_DISPLAY_WIDTH 800
#define GEO_DISPLAY_HEIGHT 480


// CONFIG
#define MOOD_PERIOD_MIN 10000
#define MOOD_PERIOD_MAX 60000
#define MOOD_IDLE 0
#define MOOD_FRIENDLY 1
#define MOOD_AGGRO 2
#define DECISION_RATE_MIN 10
#define DECISION_RATE_MAX 500

#endif